language: rust
env:
  global:
    - RUST_BACKTRACE=1
    - RUST_LOG=flo=debug
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
script: cargo test --all --no-fail-fast
